url: lsling.github.io
baseurl: ""

# Site settings
title: Laura Slingerland
# email: laura.sling@gmail.com
description: "A portfolio website"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/laura-slingerland/
  - title: facebook
    url: https://www.facebook.com/laura.slingerland
  - title: instagram
    url: https://www.instagram.com/lsling/




# Build settings
markdown: kramdown
permalink: pretty
